### ISSUE TITLE
[Feature request] Custom syntax support

### ISSUE THREAD

**Issue by Kristinita** [lattespirit/SublimeWrapper#1]
### 1. Request

It would be nice, if you add support custom syntaxes for wrapping.

### 2. Justification

Users can use non-default syntaxes for programming languages. Example syntaxes:

+ Python — [**Python Improved**](https://packagecontrol.io/packages/Python%20Improved), [**Python 3**](https://packagecontrol.io/packages/Python%203),
+ JavaScript — [**JavaScript Next**](https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax)

These syntaxes have tens of thousands downloads. I think, ignore them — is a bad practice.

### 3. Expected behavior

In `User/Wrapper.sublime-settings` file user add lines:

```json
{
    "custom_python_syntax": "Packages/Python Improved/PythonImproved.tmLanguage",
    "custom_javascript_syntax": "'Packages/JavaScriptNext - ES6 Syntax/JavaScriptNext.tmLanguage'"
}
```

Wrapper will work with these syntaxes.

Thanks.

**Comment by lattespirit** [comment]
@Kristinita Thanks for your suggestion. Now Wrapper detect the syntax of a file using Sublime default API function 'view.settings().get('syntax')', so adding more syntax name to [this constants](https://github.com/lattespirit/SublimeWrapper/blob/master/sublime_wrapper.py#L8) would be fine.
