### ISSUE TITLE
[enhancement] method extraction

### ISSUE THREAD

**Issue by ctf0** [lattespirit/SublimeWrapper#2]
is it possible for the wrapping script to check if the code is already inside a function and if yes it will then refactor/extract the code outside the current, ex.
```php
public function home()
{
    echo 'something else';

    return echo 'abc';
}
```

lets say we want to extract the `echo 'something else';` into a function, atm you will get

```php
public function home()
{
    public function other()
    {
        echo 'something else';
    }

    return echo 'abc';
}
``` 

instead it should be

```php
public function home()
{
    return echo 'abc';
}

public function other()
{
   echo 'something else';
}
```

**Comment by lattespirit** [comment]
@ctf0 Nice feature.

It's a little complicated to detect if the selected code is in a function. What's more, when we wrap `echo 'something else';` with a function, an input palette need to pop up to enter `other` function name. That's a refactoring thing.

Thanks for your suggestion.

**Comment by ctf0** [comment]
regardong the function name it wont be an issue as the cursor gets auto places right b4 the `()` so we just need to check for the scope and if its `== function` then we move to the class scope and paste the code

atm the function scope is
```
embedding.php
text.html.basic
meta.embedded.block.php
source.php
meta.class.php
meta.block.php
meta.function.php
meta.block.php
```

and class scope is
```
embedding.php
text.html.basic
meta.embedded.block.php
source.php
meta.class.php
meta.block.php
```

**Comment by bfelder** [comment]
The title of the issue should be: Implement Extraction as it is not PHP specific but would apply to any language.

I agree with @ctf0 's idea that such feature would be useful.
